volumes:
  odoo_integration_local_postgres_data: {}
  odoo_integration_local_postgres_data_backups: {}
  odoo_integration_local_redis_data: {}

  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: odoo_integration_local_django
    container_name: odoo_integration_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: odoo_integration_production_postgres
    container_name: odoo_integration_local_postgres
    volumes:
      - odoo_integration_local_postgres_data:/var/lib/postgresql/data
      - odoo_integration_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: odoo_integration_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: odoo_integration_local_redis

    volumes:
      - odoo_integration_local_redis_data:/data


  celeryworker:
    <<: *django
    image: odoo_integration_local_celeryworker
    container_name: odoo_integration_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: odoo_integration_local_celerybeat
    container_name: odoo_integration_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: odoo_integration_local_flower
    container_name: odoo_integration_local_flower
    ports:
      - '5555:5555'
    command: /start-flower

  node:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: odoo_integration_local_node
    container_name: odoo_integration_local_node
    depends_on:
      - django
    volumes:
      - .:/app:z
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/node_modules
    command: npm run dev
    ports:
      - '3000:3000'
  db:
    build:
      context: .
      dockerfile: compose/local/postgres/Dockerfile
    image: odoo_production_postgres
    container_name: postgres_odoo
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

  odoo:
    build:
      context: .
      dockerfile: ./compose/local/odoo/Dockerfile
    image: oddo
    container_name: odoo_app
    depends_on:
      - db
    ports:
      - "8069:8069"
    links:
      - "db:db"
